from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from agentboard.models import DecisionEntry, LockedPlan


@dataclass
class ApprovalResult:
    approved: bool
    policy: str = "squash"  # squash | semantic | preserve | interactive
    branch: str = ""
    rejected_reason: str = ""


POLICIES = {
    "1": "squash",
    "2": "semantic",
    "3": "preserve",
    "4": "interactive",
}


def build_pr_body(
    locked_plan: LockedPlan,
    decisions: list[DecisionEntry],
    iterations_completed: int,
    diff_stats: str = "",
) -> str:
    retries = sum(1 for d in decisions if d.phase == "review" and "RETRY" in d.verdict_source.upper())

    checklist = "\n".join(f"- [x] {item}" for item in locked_plan.goal_checklist)
    guard = "\n".join(f"- {g}" for g in locked_plan.out_of_scope_guard) or "_(none)_"

    key_decisions = []
    for d in decisions:
        if d.phase == "reflect" and d.next_strategy:
            key_decisions.append(f"- Iter {d.iter}: {d.next_strategy[:120]}")
    decisions_str = "\n".join(key_decisions) if key_decisions else "_(no retries — converged on first attempt)_"

    diff_section = f"\n## Diff Stats\n```\n{diff_stats}\n```" if diff_stats else ""

    return f"""## Problem
{locked_plan.problem}

## Architecture
{locked_plan.architecture}

## Goal Checklist
{checklist}

## Out-of-scope Guard
{guard}

## Iteration Stats
- Completed: {iterations_completed} iteration(s)
- Retries: {retries}
- Scope decision: {locked_plan.scope_decision}

## Key Decisions (from loop reflection)
{decisions_str}{diff_section}

---
🤖 Generated by [agentboard](https://github.com/anthropics/claude-code) — autonomous LLM dev board
"""


def get_diff_stats(project_root: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "diff", "--stat", "HEAD"],
            capture_output=True, text=True, cwd=str(project_root), timeout=15,
        )
        return result.stdout.strip()
    except Exception:
        return ""


def get_branch_commits(project_root: Path, branch: str, base: str = "main") -> list[str]:
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", f"{base}..{branch}"],
            capture_output=True, text=True, cwd=str(project_root), timeout=10,
        )
        return result.stdout.strip().splitlines()
    except Exception:
        return []


def apply_squash_policy(
    project_root: Path,
    branch: str,
    base_branch: str,
    policy: str,
    squash_message: str,
) -> bool:
    """Apply the chosen squash policy. Returns True on success."""
    try:
        if policy == "squash":
            return _squash_to_one(project_root, branch, base_branch, squash_message)
        elif policy == "semantic":
            # Keep as-is — caller already has semantic commits per task
            return True
        elif policy == "preserve":
            # Keep all iteration commits exactly as-is
            return True
        elif policy == "interactive":
            # Can't run interactive rebase headlessly — skip, user handles manually
            return True
        return True
    except Exception:
        return False


def _squash_to_one(project_root: Path, branch: str, base_branch: str, message: str) -> bool:
    """Soft-reset to base, re-commit everything as one commit."""
    cwd = str(project_root)
    try:
        # Reset to base branch keeping changes staged
        subprocess.run(
            ["git", "reset", "--soft", f"{base_branch}"],
            check=True, cwd=cwd, capture_output=True, timeout=15,
        )
        subprocess.run(
            ["git", "commit", "-m", message],
            check=True, cwd=cwd, capture_output=True, timeout=15,
        )
        return True
    except subprocess.CalledProcessError:
        return False
